defaults: &defaults
 
:development:
  :database:
    :adapter: sqlite3
    :database: db/development.sqlite3
    <<: *defaults

:test:
  :database:
    :database: todoneit
    <<: *defaults

:production:
  :database:
    :adapter: mysql
    :database: cartilage
    :username: cartilage
    :host: mysql.myhost.com
    :password: 
    <<: *defaults
